Fix clobbering of LogFile when set before sourcing bashlogging.

diff --git a/bashlogging b/bashlogging
--- a/bashlogging
+++ b/bashlogging
@@ -12,6 +12,12 @@
 #    #Then all that is left is to cover your script and functions with 
 #    #useful messages:
 #    Debug "ENTERING: ${FUNCNAME}()"
+#    DebugCont "Called with $# arguments"
+#    local i=0 ; for var in "$@"; do ((++i)) ; DebugCont "arg $i = ${var}"; done
+#    #DebugCont "arg 1 = $1"
+#    #DebugCont "arg 2 = $2"
+#    #DebugCont "arg 3 = $3"
+#    DebugCont "ImportantGlobalParamater = $ImportantGlobalParamater"
 #    Inform 'That important thing is being calculated now...'
 #    Warn 'The ducks weren't all in a row, but we'll forge on.'
 #    Err 'It all went horribly wrong, no value will be returned.'
@@ -23,6 +29,7 @@
 #  tee -- reads from standard input and write to standard output and files
 #  xargs
 #  bash >= 4
+#  GNU sleep -- supporting specification of floating point seconds ie, 0.1 etc.
 #
 #PROVIDES (all functions are tagged READONLY):
 #  #Message functions: for file output, prepends date & time
@@ -51,6 +58,7 @@
 #TODO: Consider making the function names more explicit by prepending Log
 #TODO: Consider making indentation on Cont[inuation] lines a standard 4 spaces.
 #TODO: Enable different "LogLevel"s for file and stdout.
+#TODO: the fraction of a second sleep works for GNU/Linux sleep, but not necessarily others...
 
 #Default logging level, controls the type of bashlogging messages reported.
 #This can be modified at any point in a calling script to increase/decrease
@@ -61,8 +69,8 @@
 #    3=provides debugging output.
 declare -i LogLevel=2
 
-#Default log file name, 
-LogFile='default_bashlogging.log'
+#Default log file name, only set if one isn't already 
+[[ "$LogFile" = "" ]] && LogFile='default_bashlogging.log'
 
 #Default type of logging to do, or more specifically the type of destination
 #for logging messages. Options are ['logfile'|'stdout'|'both'(default)], the
@@ -73,22 +81,21 @@ LogType='both'
 
 #^^^^----------- DEFAULT USER SETTINGS ABOVE THIS LINE ------------------^^^^#
 
-
-#The type of logging to do, or more specifically the type of destination for messages.
-#The options are 'both'[default] | 'logfile' | 'stdout'
-(($# > 1)) && { printf '${redbld}ERROR:${clrreset} %s\n' "$0 take only 1 arg" ; exit 1 ; }
-(($# == 1)) && declare -r LogType=$1 || declare -r LogType
-
 declare -r pad='           ' #needs to be >= number of spaces for the largest X below in %0.Xs
 declare -r redbld='\e[1;31m' # Bold Red
 declare -r grnbld='\e[1;32m' # Bold Green
-declare -r ylwbld='\e[1;33m' # Bold Orange-ish
+declare -r ylwbld='\e[1;33m' # Bold Yellow-ish
 declare -r blubld='\e[1;34m' # Bold Blue
 declare -r clrreset='\e[0m'  # Resets the colour to default
 
+#Make sure we were sourced with a reasonable number of args, exit with error message if we weren't.
+(($# > 1)) && { printf '${redbld}ERROR:${clrreset} %s\n' "$0 take only 1 arg" ; exit 1 ; }
+#If we were called with an arg use it, either way make LogType readonly so it can't be corrupted.
+(($# == 1)) && declare -r LogType=$1 || declare -r LogType
+
 if [ "$LogType" = "both" ] ; then
   #Functions defining the different logging messages, sent to logfile & stdout
-  #sleep is a hack to avoid wrong order in file when *Cont is used, and apparently processes faster leading to out of order file content. Maybe put in start of *Cont???
+  #sleep is a hack to avoid wrong order in file when *Cont is used, and apparently processes faster leading to out of order file content.
   Debug(){  ((LogLevel >= 3)) && printf "${grnbld}DEBUG:${clrreset} %s\n"   "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "s/\x1B\[([0-1];)?[0-4]{1,2}m//g" >> "$LogFile"); sleep 0.002; }
   Inform(){ ((LogLevel >= 2)) && printf "${blubld}INFO:${clrreset} %s\n"    "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "s/\x1B\[([0-1];)?[0-4]{1,2}m//g" >> "$LogFile"); sleep 0.002; }
   Warn(){   ((LogLevel >= 1)) && printf "${ylwbld}WARNING:${clrreset} %s\n" "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "s/\x1B\[([0-1];)?[0-4]{1,2}m//g" >> "$LogFile"); sleep 0.002; }
@@ -131,6 +138,32 @@ else
   printf '${redbld}ERROR:${clrreset} %s\n' 'The LogType option, if provided, must be one of: "both"; "logfile"; "stdout".'
   exit 1
 fi
+
+
+# #TODO: Add function for setting debug trace, or make this a stand alone script
+# #Prepend output with a "Simple" OR "Detailed" 
+# pre="$1"
+# #Send trace output to file
+# exec 5> "$m2kdir/${FileNameNow}_debug_trace.log"
+# BASH_XTRACEFD="5"
+# if [ "$pre" = "Simple" ] ; then
+#   PS4='${0}:${LINENO}: '
+# elif [[ "$pre" = "Detailed" ]]; then
+# 	PS4='(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]} - [${SHLVL},${BASH_SUBSHELL}, $?]'$'\n'
+# else
+# 	{ printf '${redbld}ERROR:${clrreset} %s\n' "Prepend arg must be ['Simple' | 'Detailed'] eg: $0 'Detailed'" ; exit 1 ; }
+# fi
+# set -x
+#
+#
+#
+#
+# #Then after we've finished using the file-descriptor we should close it
+# #Close fd # 5
+# exec 5<&-
+#
+#
+
 
 # #Make the functions defined here readonly to prevent clobbering by calling script.
 # readonly -f Debug
