Adds stderr as an output option.

diff --git a/bashlogging b/bashlogging
--- a/bashlogging
+++ b/bashlogging
@@ -53,19 +53,15 @@
 # Originally Written: 2015-11-27
 #
 
-#TODO: Consider making all terminal output going to stderr
 #TODO: Consider adding an AutoElevate ['Enabled'|'Disabled'] option, which automatically raises 
 #      the LogLevel to 2 in the event of warnings and 3 in the event of errors.
-#TODO: Consider making the function names more explicit by prepending Log
 #TODO: Consider making indentation on Cont[inuation] lines a standard 4 spaces.
 #TODO: Enable different "LogLevel"s for file and stdout.
-#TODO: the fraction of a second sleep works for GNU/Linux sleep, but not necessarily others...
-#TODO: Consider redirecting the stdout component of the Err functions to stderr
+#TODO: the fraction of a second sleep works for GNU/Linux sleep, but not necessarily others... Solve order preservation some other way...
 #TODO: Consider copying stderr generated by the script to log file: see http://stackoverflow.com/questions/637827/redirect-stderr-and-stdout-in-a-bash-script
 #    exec 4>&2 2> >(tee >(xargs --null printf "[$(date +%FT%T)] ERROR: %s\n" >> "$LogFile") >&4)
 #TODO: Consider conforming to this: https://google.github.io/styleguide/shell.xml
 #      variable names ALLCAPS, function names all_lower_case
-
 
 #Default logging level, controls the type of bashlogging messages reported.
 #This can be modified at any point in a calling script to increase/decrease
@@ -95,21 +91,24 @@ declare -gr ylwbld='\e[1;33m' # Bold Yellow-ish
 declare -gr blubld='\e[1;34m' # Bold Blue
 declare -gr clrreset='\e[0m'  # Resets the colour to default
 
-#DEBUG_CLR='\e[1;32mERROR:\e[0m'
+#declare -gr DEBUG_CLR='\e[1;32mDEBUG:\e[0m'  # Bold Green
+#declare -gr INFO_CLR='\e[1;34mINFO:\e[0m'    # Bold Blue
+#declare -gr WARN_CLR='\e[1;33mWARNING:\e[0m' # Bold Yellow-ish
+#declare -gr ERROR_CLR='\e[1;31mERROR:\e[0m'  # Bold Red
 
 #Make sure we were sourced with a reasonable number of args, return with error message if we weren't.
 (($# > 1)) && { printf "${redbld}ERROR:${clrreset} %s\n" "${BASH_SOURCE[0]} takes at most 1 arg" ; return 1 ; }
 #If we were called with an arg use it, either way make LogType readonly so it can't be corrupted.
-if (($# == 1)) && [[ "$1" =~ ^(logfile|stdout|both)$ ]] ; then
+if (($# == 1)) && [[ "$1" =~ ^(logfile|file|stdout|stderr|both|filestdout|filestderr)$ ]] ; then
   declare -gr LogType="$1"
-elif (($# == 0)) && [[ "$LogType" =~ ^(logfile|stdout|both)$ ]] ; then
+elif (($# == 0)) && [[ "$LogType" =~ ^(logfile|file|stdout|stderr|both|filestdout|filestderr)$ ]] ; then
   declare -gr LogType
 else
   printf "${redbld}ERROR:${clrreset} %s\n" "For ${BASH_SOURCE[0]} LogType must be 'logfile'|'stdout'|'both'."
   return 1
 fi
 
-if [ "$LogType" = "both" ] ; then
+if[[ "$LogType" = @(both|filestdout) ]] ; then
   #Functions defining the different logging messages, sent to logfile & stdout.
   #sleep is a hack to avoid wrong order in file when *Cont is used, and apparently processes faster leading to out of order file content.
   Debug(){  ((LogLevel >= 3)) && printf "${grnbld}DEBUG:${clrreset} %s\n"   "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "s/\x1B\[([0-1];)?[0-4]{1,2}m//g" >> "$LogFile"); sleep 0.002; }
@@ -127,7 +126,25 @@ if [ "$LogType" = "both" ] ; then
   #Use to pipe output from another command to logs, eg: command 2>&1 | err_pipe "command: "
   err_pipe(){ while IFS='' read -r msg; do msg="$1$msg"; ((LogLevel >= 0)) && printf '%s\n' "$msg" | tee -a "$LogFile"; done; }
 
-elif [ "$LogType" = "stdout" ] ; then
+if[[ "$LogType" = 'filestderr') ]] ; then
+  #Functions defining the different logging messages, sent to logfile & stderr.
+  #sleep is a hack to avoid wrong order in file when *Cont is used, and apparently processes faster leading to out of order file content.
+  Debug(){  ((LogLevel >= 3)) && printf "${grnbld}DEBUG:${clrreset} %s\n"   "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "s/\x1B\[([0-1];)?[0-4]{1,2}m//g" >> "$LogFile") 1>&2 ; sleep 0.002; }
+  Inform(){ ((LogLevel >= 2)) && printf "${blubld}INFO:${clrreset} %s\n"    "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "s/\x1B\[([0-1];)?[0-4]{1,2}m//g" >> "$LogFile") 1>&2 ; sleep 0.002; }
+  Warn(){   ((LogLevel >= 1)) && printf "${ylwbld}WARNING:${clrreset} %s\n" "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "s/\x1B\[([0-1];)?[0-4]{1,2}m//g" >> "$LogFile") 1>&2 ; sleep 0.002; }
+  Err(){    ((LogLevel >= 0)) && printf "${redbld}ERROR:${clrreset} %s\n"   "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "s/\x1B\[([0-1];)?[0-4]{1,2}m//g" >> "$LogFile") 1>&2 ; sleep 0.002; }
+  #Func: #Checks LogLevel is appropriate #Prepends msg with Type     #Pipes to stderr & Command as fake file: prepend Date&Time then Strip colour tags           #Redirect to log file  #Wait so order preserved
+
+  #Use for multiple lines of a single message, sent to logfile & stderr
+  DebugCont(){  ((LogLevel >= 3)) && printf '%0.7s%s\n' "$pad" "$1" | tee -a "$LogFile" 1>&2 ; }
+  InformCont(){ ((LogLevel >= 2)) && printf '%0.6s%s\n' "$pad" "$1" | tee -a "$LogFile" 1>&2 ; }
+  WarnCont(){   ((LogLevel >= 1)) && printf '%0.9s%s\n' "$pad" "$1" | tee -a "$LogFile" 1>&2 ; }
+  ErrCont(){    ((LogLevel >= 0)) && printf '%0.7s%s\n' "$pad" "$1" | tee -a "$LogFile" 1>&2 ; }
+
+  #Use to pipe output from another command to logs, eg: command 2>&1 | err_pipe "command: "
+  err_pipe(){ while IFS='' read -r msg; do msg="$1$msg"; ((LogLevel >= 0)) && printf '%s\n' "$msg" | tee -a "$LogFile" 1>&2 ; done; }
+
+elif [[ "$LogType" = 'stdout' ]] ; then
   #Functions defining the different logging messages, no-logfile==only-stdout
   Debug(){  ((LogLevel >= 3)) && printf "${grnbld}DEBUG:${clrreset} %s\n"   "$1" ; }
   Inform(){ ((LogLevel >= 2)) && printf "${blubld}INFO:${clrreset} %s\n"    "$1" ; }
@@ -143,8 +160,24 @@ elif [ "$LogType" = "stdout" ] ; then
   #Use to pipe output from another command to logs, eg: command 2>&1 | err_pipe "command: "
   err_pipe(){ while IFS='' read -r msg; do msg="$1$msg"; ((LogLevel >= 0)) && printf '%s\n' "$msg" ; done; }
 
-elif [ "$LogType" = "logfile" ] ; then
-  #Functions defining the different logging messages, no-stdout==only-logfile
+elif [[ "$LogType" = 'stderr' ]] ; then
+  #Functions defining the different logging messages, no-logfile==only-stderr
+  Debug(){  ((LogLevel >= 3)) && printf "${grnbld}DEBUG:${clrreset} %s\n"   "$1" 1>&2 ; }
+  Inform(){ ((LogLevel >= 2)) && printf "${blubld}INFO:${clrreset} %s\n"    "$1" 1>&2 ; }
+  Warn(){   ((LogLevel >= 1)) && printf "${ylwbld}WARNING:${clrreset} %s\n" "$1" 1>&2 ; }
+  Err(){    ((LogLevel >= 0)) && printf "${redbld}ERROR:${clrreset} %s\n"   "$1" 1>&2 ; }
+
+  #Use for multiple lines of a single message, no-logfile==only-stderr
+  DebugCont(){  ((LogLevel >= 3)) && printf '%0.7s%s\n' "$pad" "$1" 1>&2 ; }
+  InformCont(){ ((LogLevel >= 2)) && printf '%0.6s%s\n' "$pad" "$1" 1>&2 ; }
+  WarnCont(){   ((LogLevel >= 1)) && printf '%0.9s%s\n' "$pad" "$1" 1>&2 ; }
+  ErrCont(){    ((LogLevel >= 0)) && printf '%0.7s%s\n' "$pad" "$1" 1>&2 ; }
+
+  #Use to pipe output from another command to logs, eg: command 2>&1 | err_pipe "command: "
+  err_pipe(){ while IFS='' read -r msg; do msg="$1$msg"; ((LogLevel >= 0)) && printf '%s\n' "$msg" 1>&2 ; done; }
+
+elif [[ "$LogType" = @(logfile|file) ]] ; then
+  #Functions defining the different logging messages, no-stdout|stderr==only-logfile
   Debug(){  ((LogLevel >= 3)) && printf "[$(date +%FT%T)] DEBUG: %s\n"   "$1" >> "$LogFile"; }
   Inform(){ ((LogLevel >= 2)) && printf "[$(date +%FT%T)] INFO: %s\n"    "$1" >> "$LogFile"; }
   Warn(){   ((LogLevel >= 1)) && printf "[$(date +%FT%T)] WARNING: %s\n" "$1" >> "$LogFile"; }
@@ -160,7 +193,7 @@ elif [ "$LogType" = "logfile" ] ; then
   err_pipe(){ while IFS='' read -r msg; do msg="$1$msg"; ((LogLevel >= 0)) && printf '%s\n' "$msg" >> "$LogFile"; done; }
 
 else
-  printf "${redbld}ERROR:${clrreset} %s\n" 'The LogType option, if provided, must be one of: "both"; "logfile"; "stdout".'
+  printf "${redbld}ERROR:${clrreset} %s\n" 'The LogType option, if provided, must be one of: "file"; "stdout"; "stderr"; "filestdout"; "filestderr".'
   return 1
 fi
 
