Fixes implicit fall-back interpretation with explicit escape.

diff --git a/bashlogging b/bashlogging
--- a/bashlogging
+++ b/bashlogging
@@ -80,7 +80,7 @@
 #TODO: Enable different "LOGLEVEL"s for file and stdout/stderr.
 #TODO: the fraction of a second sleep works for GNU/Linux sleep, but not necessarily others... Solve order preservation some other way...
 #TODO: Consider copying stderr generated by the script to log file: see http://stackoverflow.com/questions/637827/redirect-stderr-and-stdout-in-a-bash-script
-#    exec 4>&2 2> >(tee >(xargs --null printf "[$(date +%FT%T)] ERROR: %s\n" >> "$LOGFILE") >&4)
+#    exec 4>&2 2> >(tee >(xargs --null printf "[$(date +%FT%T)] ERROR: %s\\n" >> "$LOGFILE") >&4)
 #TODO: Consider whether it's worth making the functions readonly to avoid accidental modification.
 
 #Default logging level, controls the type of bashlogging messages reported.
@@ -113,17 +113,17 @@ declare -gr STRIP_CLR='s/\x1B\[([0-1];)?[0-4]{1,2}m//g' #A regex to strip colour
 
 #Return an error message if LOGTYPE isn't set correctly.
 if [[ ! "$LOGTYPE" =~ ^(logfile|file|stdout|stderr|both|filestdout|filestderr)$ ]]; then
-  printf "$ERROR_CLR %s\n" "For ${BASH_SOURCE[0]} LOGTYPE must be ['file'|'stdout'|'stderr'|'filestdout'|'filestderr'(default)]."
+  printf "$ERROR_CLR %s\\n" "For ${BASH_SOURCE[0]} LOGTYPE must be ['file'|'stdout'|'stderr'|'filestdout'|'filestderr'(default)]."
   return 1
 fi
 
 if [[ "$LOGTYPE" = @(both|filestdout) ]] ; then
   #Functions defining the different logging messages, sent to logfile & stdout.
   #sleep is a hack to avoid wrong order in file when *Cont is used, and apparently processes faster leading to out of order file content.
-  debug(){  ((LOGLEVEL >= 3)) && printf "$DEBUG_CLR %s\n" "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LOGFILE"); sleep 0.002; }
-  inform(){ ((LOGLEVEL >= 2)) && printf "$INFO_CLR %s\n"  "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LOGFILE"); sleep 0.002; }
-  warn(){   ((LOGLEVEL >= 1)) && printf "$WARN_CLR %s\n"  "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LOGFILE"); sleep 0.002; }
-  err(){    ((LOGLEVEL >= 0)) && printf "$ERROR_CLR %s\n" "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LOGFILE"); sleep 0.002; }
+  debug(){  ((LOGLEVEL >= 3)) && printf "$DEBUG_CLR %s\\n" "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LOGFILE"); sleep 0.002; }
+  inform(){ ((LOGLEVEL >= 2)) && printf "$INFO_CLR %s\\n"  "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LOGFILE"); sleep 0.002; }
+  warn(){   ((LOGLEVEL >= 1)) && printf "$WARN_CLR %s\\n"  "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LOGFILE"); sleep 0.002; }
+  err(){    ((LOGLEVEL >= 0)) && printf "$ERROR_CLR %s\\n" "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LOGFILE"); sleep 0.002; }
   #Func: #If LOGLEVEL appropriate #Prepend msg with Type #Pipe to stdout & process substitution: prepend Date&Time, strip colour tags #Redirect to file #Wait so order preserved
 
   #Use for multiple lines of a single message, sent to logfile & stdout
@@ -138,10 +138,10 @@ if [[ "$LOGTYPE" = @(both|filestdout) ]] ; then
 elif [[ "$LOGTYPE" = 'filestderr' ]] ; then
   #Functions defining the different logging messages, sent to logfile & stderr.
   #sleep is a hack to avoid wrong order in file when *Cont is used, and apparently processes faster leading to out of order file content.
-  debug(){  ((LOGLEVEL >= 3)) && printf "$DEBUG_CLR %s\n" "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LOGFILE") 1>&2 ; sleep 0.002; }
-  inform(){ ((LOGLEVEL >= 2)) && printf "$INFO_CLR %s\n"  "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LOGFILE") 1>&2 ; sleep 0.002; }
-  warn(){   ((LOGLEVEL >= 1)) && printf "$WARN_CLR %s\n"  "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LOGFILE") 1>&2 ; sleep 0.002; }
-  err(){    ((LOGLEVEL >= 0)) && printf "$ERROR_CLR %s\n" "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LOGFILE") 1>&2 ; sleep 0.002; }
+  debug(){  ((LOGLEVEL >= 3)) && printf "$DEBUG_CLR %s\\n" "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LOGFILE") 1>&2 ; sleep 0.002; }
+  inform(){ ((LOGLEVEL >= 2)) && printf "$INFO_CLR %s\\n"  "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LOGFILE") 1>&2 ; sleep 0.002; }
+  warn(){   ((LOGLEVEL >= 1)) && printf "$WARN_CLR %s\\n"  "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LOGFILE") 1>&2 ; sleep 0.002; }
+  err(){    ((LOGLEVEL >= 0)) && printf "$ERROR_CLR %s\\n" "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LOGFILE") 1>&2 ; sleep 0.002; }
   #Func: #If LOGLEVEL appropriate #Prepend msg with Type #Pipe to stderr & process substitution: prepend Date&Time, strip colour tags #Redirect to file #Wait so order preserved
 
   #Use for multiple lines of a single message, sent to logfile & stderr
@@ -155,10 +155,10 @@ elif [[ "$LOGTYPE" = 'filestderr' ]] ; then
 
 elif [[ "$LOGTYPE" = 'stdout' ]] ; then
   #Functions defining the different logging messages, no-logfile==only-stdout
-  debug(){  ((LOGLEVEL >= 3)) && printf "$DEBUG_CLR %s\n" "$1" ; }
-  inform(){ ((LOGLEVEL >= 2)) && printf "$INFO_CLR %s\n"  "$1" ; }
-  warn(){   ((LOGLEVEL >= 1)) && printf "$WARN_CLR %s\n"  "$1" ; }
-  err(){    ((LOGLEVEL >= 0)) && printf "$ERROR_CLR %s\n" "$1" ; }
+  debug(){  ((LOGLEVEL >= 3)) && printf "$DEBUG_CLR %s\\n" "$1" ; }
+  inform(){ ((LOGLEVEL >= 2)) && printf "$INFO_CLR %s\\n"  "$1" ; }
+  warn(){   ((LOGLEVEL >= 1)) && printf "$WARN_CLR %s\\n"  "$1" ; }
+  err(){    ((LOGLEVEL >= 0)) && printf "$ERROR_CLR %s\\n" "$1" ; }
 
   #Use for multiple lines of a single message, no-logfile==only-stdout
   debugcont(){  ((LOGLEVEL >= 3)) && printf '%0.7s%s\n' "$pad" "$1" ; }
@@ -171,10 +171,10 @@ elif [[ "$LOGTYPE" = 'stdout' ]] ; then
 
 elif [[ "$LOGTYPE" = 'stderr' ]] ; then
   #Functions defining the different logging messages, no-logfile==only-stderr
-  debug(){  ((LOGLEVEL >= 3)) && printf "$DEBUG_CLR %s\n" "$1" 1>&2 ; }
-  inform(){ ((LOGLEVEL >= 2)) && printf "$INFO_CLR %s\n"  "$1" 1>&2 ; }
-  warn(){   ((LOGLEVEL >= 1)) && printf "$WARN_CLR %s\n"  "$1" 1>&2 ; }
-  err(){    ((LOGLEVEL >= 0)) && printf "$ERROR_CLR %s\n" "$1" 1>&2 ; }
+  debug(){  ((LOGLEVEL >= 3)) && printf "$DEBUG_CLR %s\\n" "$1" 1>&2 ; }
+  inform(){ ((LOGLEVEL >= 2)) && printf "$INFO_CLR %s\\n"  "$1" 1>&2 ; }
+  warn(){   ((LOGLEVEL >= 1)) && printf "$WARN_CLR %s\\n"  "$1" 1>&2 ; }
+  err(){    ((LOGLEVEL >= 0)) && printf "$ERROR_CLR %s\\n" "$1" 1>&2 ; }
 
   #Use for multiple lines of a single message, no-logfile==only-stderr
   debugcont(){  ((LOGLEVEL >= 3)) && printf '%0.7s%s\n' "$pad" "$1" 1>&2 ; }
@@ -187,10 +187,10 @@ elif [[ "$LOGTYPE" = 'stderr' ]] ; then
 
 elif [[ "$LOGTYPE" = @(logfile|file) ]] ; then
   #Functions defining the different logging messages, no-stdout|stderr==only-logfile
-  debug(){  ((LOGLEVEL >= 3)) && printf "[$(date +%FT%T)] DEBUG: %s\n"   "$1" >> "$LOGFILE"; }
-  inform(){ ((LOGLEVEL >= 2)) && printf "[$(date +%FT%T)] INFO: %s\n"    "$1" >> "$LOGFILE"; }
-  warn(){   ((LOGLEVEL >= 1)) && printf "[$(date +%FT%T)] WARNING: %s\n" "$1" >> "$LOGFILE"; }
-  err(){    ((LOGLEVEL >= 0)) && printf "[$(date +%FT%T)] ERROR: %s\n"   "$1" >> "$LOGFILE"; }
+  debug(){  ((LOGLEVEL >= 3)) && printf "[$(date +%FT%T)] DEBUG: %s\\n"   "$1" >> "$LOGFILE"; }
+  inform(){ ((LOGLEVEL >= 2)) && printf "[$(date +%FT%T)] INFO: %s\\n"    "$1" >> "$LOGFILE"; }
+  warn(){   ((LOGLEVEL >= 1)) && printf "[$(date +%FT%T)] WARNING: %s\\n" "$1" >> "$LOGFILE"; }
+  err(){    ((LOGLEVEL >= 0)) && printf "[$(date +%FT%T)] ERROR: %s\\n"   "$1" >> "$LOGFILE"; }
 
   #Use for multiple lines of a single message, no-stdout==only-logfile
   debugcont(){  ((LOGLEVEL >= 3)) && printf '%0.7s%s\n' "$pad" "$1" >> "$LOGFILE"; }
@@ -202,7 +202,7 @@ elif [[ "$LOGTYPE" = @(logfile|file) ]] ; then
   err_pipe(){ while IFS='' read -r msg; do msg="$1$msg"; ((LOGLEVEL >= 0)) && printf '%s\n' "$msg" >> "$LOGFILE"; done; }
 
 else
-  printf "$ERROR_CLR %s\n" 'The LOGTYPE option, if provided, must be one of: "file"; "stdout"; "stderr"; "filestdout"; "filestderr".'
+  printf "$ERROR_CLR %s\\n" 'The LOGTYPE option, if provided, must be one of: "file"; "stdout"; "stderr"; "filestdout"; "filestderr".'
   return 1
 fi
 
@@ -234,7 +234,7 @@ set_trace(){
   elif [[ "$pre" = "Detailed" ]]; then
     PS4='(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]} - [${SHLVL},${BASH_SUBSHELL}, $?]'$'\n'
   else
-    { printf "$ERROR_CLR %s\n" "Prepend arg must be ['Simple' | 'Detailed'] eg: ${BASH_SOURCE[0]} 'Detailed'" ; return 1 ; }
+    { printf "$ERROR_CLR %s\\n" "Prepend arg must be ['Simple' | 'Detailed'] eg: ${BASH_SOURCE[0]} 'Detailed'" ; return 1 ; }
   fi
   set -x
 }
