Fleshes out the set_trace() function... need to test it actually works.

diff --git a/bashlogging b/bashlogging
--- a/bashlogging
+++ b/bashlogging
@@ -52,8 +52,8 @@
 #  err_pipe -- For LogLevel >= 0, write piped input to logs.
 #
 #DESCRIPTION:
-# Defines a few functions for fine grained control of logging information.
-# Writes different types of messages based on LogLevel. The messages are 
+# Defines several functions for fine grained control of logging information.
+# Writes different types of messages based on LogLevel. The messages are
 # sent to either stdout, stderr, file, or both based on the LogType argument.
 # The file output is prepended with date & time -- stdout/stderr aren't.
 #
@@ -102,6 +102,7 @@ declare -gr STRIP_CLR='s/\x1B\[([0-1];)?[0-4]{1,2}m//g' #A regex to strip colour
 
 #Make sure we were sourced with a reasonable number of args, return with error message if we weren't.
 (($# > 1)) && { printf "$ERROR_CLR %s\n" "${BASH_SOURCE[0]} takes at most 1 arg" ; return 1 ; }
+
 #If we were called with an arg use it, either way make LogType readonly so it can't be corrupted.
 if (($# == 1)) && [[ "$1" =~ ^(logfile|file|stdout|stderr|both|filestdout|filestderr)$ ]] ; then
   declare -gr LogType="$1"
@@ -201,30 +202,40 @@ else
   return 1
 fi
 
+# #TODO: Check this actually works... seems like a good idea...
+#set_trace 'Detailed' "$m2kdir/${FileNameNow}_debug_trace.log"
+#Set debug trace, output to its own file via file-descriptor 5
+set_trace(){
+  #Take prepend setting from command, default to "Simple".
+  if [[ -n "$1" ]]; then pre="$1"; else pre='Simple'; fi
 
-# #TODO: Add function for setting debug trace, or make this a stand alone script
-# #Prepend output with a "Simple" OR "Detailed" 
-# pre="$1"
-# #Send trace output to file
-# exec 5> "$m2kdir/${FileNameNow}_debug_trace.log"
-# BASH_XTRACEFD="5"
-# if [ "$pre" = "Simple" ] ; then
-#   PS4='${0}:${LINENO}: '
-# elif [[ "$pre" = "Detailed" ]]; then
-# 	PS4='(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]} - [${SHLVL},${BASH_SUBSHELL}, $?]'$'\n'
-# else
-# 	{ printf "$ERROR_CLR %s\n" "Prepend arg must be ['Simple' | 'Detailed'] eg: ${BASH_SOURCE[0]} 'Detailed'" ; return 1 ; }
-# fi
-# set -x
-#
-#
-#
-#
-# #Then after we've finished using the file-descriptor we should close it
-# #Close fd # 5
-# exec 5<&-
-#
-#
+  #Send trace output to file
+  if [[ -n "$2" ]]; then
+    local FileName="$2"
+  else
+    local FileName="$(date +%FT%H%M%S)_debug_trace.log"
+  fi
+  exec 5> "$FileName"
+  BASH_XTRACEFD="5"
+
+  #Prepend output with a "Simple" OR "Detailed"
+  if [[ "$pre" = "Simple" ]]; then
+    PS4='${0}:${LINENO}: '
+  elif [[ "$pre" = "Detailed" ]]; then
+    PS4='(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]} - [${SHLVL},${BASH_SUBSHELL}, $?]'$'\n'
+  else
+    { printf "$ERROR_CLR %s\n" "Prepend arg must be ['Simple' | 'Detailed'] eg: ${BASH_SOURCE[0]} 'Detailed'" ; return 1 ; }
+  fi
+  set -x
+}
+
+#Unset the debug trace, closing file-descriptor 5
+unset_trace(){
+ #Close fd # 5
+ #exec 5<&-
+ unset BASH_XTRACEFD #unsetting BASH_XTRACEFD has the side effect of closing the file-descriptor it had been pointed to...
+}
+
 
 # #Make the functions defined here readonly to prevent clobbering by calling script.
 # readonly -f Debug
