Tidies colour related variables. Reviews comments.

diff --git a/bashlogging b/bashlogging
--- a/bashlogging
+++ b/bashlogging
@@ -3,8 +3,8 @@
 #USAGE:
 #  #Source the file to get access to all the variable and function definitions.
 #  source bashlogging [LogType]
-#  #the optional LogType argument ['stdout'|'logfile'|'both'(default)] directs
-#  # output to stdout, file or both. This can only be set while "source"ing.
+#  #LogType argument ['stdout'|'stderr'|'file'|'stdoutfile'(default)|'stderrfile']
+#  #directs output to stdout, file or both. This can only be set while "source"ing.
 #  #Then you can override default LogFile and LogLevel to suit your needs.
 #  LogFile='path/to/mylogfile.log'
 #  LogLevel=3  #I have a problem with my script that I need to identify.
@@ -19,10 +19,16 @@
 #    #DebugCont "arg 3 = $3"
 #    DebugCont "ImportantGlobalParamater = $ImportantGlobalParamater"
 #    Inform 'That important thing is being calculated now...'
+#    #You can pipe another commands stdout to your logs
+#    command1 | err_pipe "command1: "
+#    #Or with stderr as well
+#    command1 2>&1 | err_pipe "command1: "
+#    #If using one of the stderr or file-only LogTypes, you can message mid pipe
+#    command1 | tee >(Debug "Stuff is happening") | command2
 #    Warn 'The ducks weren't all in a row, but we'll forge on.'
 #    Err 'It all went horribly wrong, no value will be returned.'
 #    ErrCont "The value of x was $y and j was $z, try passing q to ${FUNCNAME}()"
-#    ErrCont 'You might also need to chmod yourfile.txt and do a rain dance.'
+#    ErrCont "You may also need to 'chmod a+rwx yourfile.txt' and do a rain dance."
 #  }
 #
 #REQUIRES:
@@ -31,7 +37,7 @@
 #  bash >= 4
 #  GNU sleep -- supporting specification of floating point seconds ie, 0.1 etc.
 #
-#PROVIDES (all functions are tagged READONLY):
+#PROVIDES:
 #  #Message functions: for file output, prepends date & time
 #  Debug  -- For LogLevel >= 3, writes messages prepended with "DEBUG: "
 #  Inform -- For LogLevel >= 2, writes messages prepended with "INFORM: "
@@ -42,12 +48,14 @@
 #  InformCont -- Continues a LogLevel 2 message.
 #  WarnCont   -- Continues a LogLevel 1 message.
 #  ErrCont    -- Continues a LogLevel 0 message.
+#  #Pipe output from another command to logs, eg: command 2>&1 | err_pipe "command: "
+#  err_pipe -- For LogLevel >= 0, write piped input to logs.
 #
 #DESCRIPTION:
 # Defines a few functions for fine grained control of logging information.
 # Writes different types of messages based on LogLevel. The messages are 
-# sent to either stdout, file, or both based on the LogType argument. The
-# file output is prepended with date & time -- stdout isn't.
+# sent to either stdout, stderr, file, or both based on the LogType argument.
+# The file output is prepended with date & time -- stdout/stderr aren't.
 #
 # Author: Stuart A. Knock
 # Originally Written: 2015-11-27
@@ -62,6 +70,7 @@
 #    exec 4>&2 2> >(tee >(xargs --null printf "[$(date +%FT%T)] ERROR: %s\n" >> "$LogFile") >&4)
 #TODO: Consider conforming to this: https://google.github.io/styleguide/shell.xml
 #      variable names ALLCAPS, function names all_lower_case
+#TODO: Consider whether it's worth making the functions readonly to avoid accidental modification.
 
 #Default logging level, controls the type of bashlogging messages reported.
 #This can be modified at any point in a calling script to increase/decrease
@@ -85,37 +94,32 @@ if [[ -z "$LogLevel" ]]; then declare -gi LogLevel=2; else declare -gi LogLevel;
 #^^^^----------- DEFAULT USER SETTINGS ABOVE THIS LINE ------------------^^^^#
 
 declare -gr pad='           ' #needs to be >= number of spaces for the largest X below in %0.Xs
-declare -gr redbld='\e[1;31m' # Bold Red
-declare -gr grnbld='\e[1;32m' # Bold Green
-declare -gr ylwbld='\e[1;33m' # Bold Yellow-ish
-declare -gr blubld='\e[1;34m' # Bold Blue
-declare -gr clrreset='\e[0m'  # Resets the colour to default
-
-#declare -gr DEBUG_CLR='\e[1;32mDEBUG:\e[0m'  # Bold Green
-#declare -gr INFO_CLR='\e[1;34mINFO:\e[0m'    # Bold Blue
-#declare -gr WARN_CLR='\e[1;33mWARNING:\e[0m' # Bold Yellow-ish
-#declare -gr ERROR_CLR='\e[1;31mERROR:\e[0m'  # Bold Red
+declare -gr DEBUG_CLR='\e[1;32mDEBUG:\e[0m'  # Bold Green
+declare -gr INFO_CLR='\e[1;34mINFO:\e[0m'    # Bold Blue
+declare -gr WARN_CLR='\e[1;33mWARNING:\e[0m' # Bold Yellow-ish
+declare -gr ERROR_CLR='\e[1;31mERROR:\e[0m'  # Bold Red
+declare -gr STRIP_CLR='s/\x1B\[([0-1];)?[0-4]{1,2}m//g' #A regex to strip colour tags
 
 #Make sure we were sourced with a reasonable number of args, return with error message if we weren't.
-(($# > 1)) && { printf "${redbld}ERROR:${clrreset} %s\n" "${BASH_SOURCE[0]} takes at most 1 arg" ; return 1 ; }
+(($# > 1)) && { printf "$ERROR_CLR %s\n" "${BASH_SOURCE[0]} takes at most 1 arg" ; return 1 ; }
 #If we were called with an arg use it, either way make LogType readonly so it can't be corrupted.
 if (($# == 1)) && [[ "$1" =~ ^(logfile|file|stdout|stderr|both|filestdout|filestderr)$ ]] ; then
   declare -gr LogType="$1"
 elif (($# == 0)) && [[ "$LogType" =~ ^(logfile|file|stdout|stderr|both|filestdout|filestderr)$ ]] ; then
   declare -gr LogType
 else
-  printf "${redbld}ERROR:${clrreset} %s\n" "For ${BASH_SOURCE[0]} LogType must be 'logfile'|'stdout'|'both'."
+  printf "$ERROR_CLR %s\n" "For ${BASH_SOURCE[0]} LogType must be 'logfile'|'stdout'|'both'."
   return 1
 fi
 
 if[[ "$LogType" = @(both|filestdout) ]] ; then
   #Functions defining the different logging messages, sent to logfile & stdout.
   #sleep is a hack to avoid wrong order in file when *Cont is used, and apparently processes faster leading to out of order file content.
-  Debug(){  ((LogLevel >= 3)) && printf "${grnbld}DEBUG:${clrreset} %s\n"   "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "s/\x1B\[([0-1];)?[0-4]{1,2}m//g" >> "$LogFile"); sleep 0.002; }
-  Inform(){ ((LogLevel >= 2)) && printf "${blubld}INFO:${clrreset} %s\n"    "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "s/\x1B\[([0-1];)?[0-4]{1,2}m//g" >> "$LogFile"); sleep 0.002; }
-  Warn(){   ((LogLevel >= 1)) && printf "${ylwbld}WARNING:${clrreset} %s\n" "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "s/\x1B\[([0-1];)?[0-4]{1,2}m//g" >> "$LogFile"); sleep 0.002; }
-  Err(){    ((LogLevel >= 0)) && printf "${redbld}ERROR:${clrreset} %s\n"   "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "s/\x1B\[([0-1];)?[0-4]{1,2}m//g" >> "$LogFile"); sleep 0.002; }
-  #Func: #Checks LogLevel is appropriate #Prepends msg with Type     #Pipes to stdout & Command as fake file: prepend Date&Time then Strip colour tags           #Redirect to log file  #Wait so order preserved
+  Debug(){  ((LogLevel >= 3)) && printf "$DEBUG_CLR %s\n" "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LogFile"); sleep 0.002; }
+  Inform(){ ((LogLevel >= 2)) && printf "$INFO_CLR %s\n"  "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LogFile"); sleep 0.002; }
+  Warn(){   ((LogLevel >= 1)) && printf "$WARN_CLR %s\n"  "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LogFile"); sleep 0.002; }
+  Err(){    ((LogLevel >= 0)) && printf "$ERROR_CLR %s\n" "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LogFile"); sleep 0.002; }
+  #Func: #If LogLevel appropriate #Prepend msg with Type #Pipe to stdout & process substitution: prepend Date&Time, strip colour tags #Redirect to file #Wait so order preserved
 
   #Use for multiple lines of a single message, sent to logfile & stdout
   DebugCont(){  ((LogLevel >= 3)) && printf '%0.7s%s\n' "$pad" "$1" | tee -a "$LogFile"; }
@@ -129,11 +133,11 @@ if[[ "$LogType" = @(both|filestdout) ]] ; then
 if[[ "$LogType" = 'filestderr') ]] ; then
   #Functions defining the different logging messages, sent to logfile & stderr.
   #sleep is a hack to avoid wrong order in file when *Cont is used, and apparently processes faster leading to out of order file content.
-  Debug(){  ((LogLevel >= 3)) && printf "${grnbld}DEBUG:${clrreset} %s\n"   "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "s/\x1B\[([0-1];)?[0-4]{1,2}m//g" >> "$LogFile") 1>&2 ; sleep 0.002; }
-  Inform(){ ((LogLevel >= 2)) && printf "${blubld}INFO:${clrreset} %s\n"    "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "s/\x1B\[([0-1];)?[0-4]{1,2}m//g" >> "$LogFile") 1>&2 ; sleep 0.002; }
-  Warn(){   ((LogLevel >= 1)) && printf "${ylwbld}WARNING:${clrreset} %s\n" "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "s/\x1B\[([0-1];)?[0-4]{1,2}m//g" >> "$LogFile") 1>&2 ; sleep 0.002; }
-  Err(){    ((LogLevel >= 0)) && printf "${redbld}ERROR:${clrreset} %s\n"   "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "s/\x1B\[([0-1];)?[0-4]{1,2}m//g" >> "$LogFile") 1>&2 ; sleep 0.002; }
-  #Func: #Checks LogLevel is appropriate #Prepends msg with Type     #Pipes to stderr & Command as fake file: prepend Date&Time then Strip colour tags           #Redirect to log file  #Wait so order preserved
+  Debug(){  ((LogLevel >= 3)) && printf "$DEBUG_CLR %s\n" "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LogFile") 1>&2 ; sleep 0.002; }
+  Inform(){ ((LogLevel >= 2)) && printf "$INFO_CLR %s\n"  "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LogFile") 1>&2 ; sleep 0.002; }
+  Warn(){   ((LogLevel >= 1)) && printf "$WARN_CLR %s\n"  "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LogFile") 1>&2 ; sleep 0.002; }
+  Err(){    ((LogLevel >= 0)) && printf "$ERROR_CLR %s\n" "$1" | tee >(xargs --null printf "[$(date +%FT%T)] %s" | sed -r "$STRIP_CLR" >> "$LogFile") 1>&2 ; sleep 0.002; }
+  #Func: #If LogLevel appropriate #Prepend msg with Type #Pipe to stderr & process substitution: prepend Date&Time, strip colour tags #Redirect to file #Wait so order preserved
 
   #Use for multiple lines of a single message, sent to logfile & stderr
   DebugCont(){  ((LogLevel >= 3)) && printf '%0.7s%s\n' "$pad" "$1" | tee -a "$LogFile" 1>&2 ; }
@@ -146,10 +150,10 @@ if[[ "$LogType" = 'filestderr') ]] ; then
 
 elif [[ "$LogType" = 'stdout' ]] ; then
   #Functions defining the different logging messages, no-logfile==only-stdout
-  Debug(){  ((LogLevel >= 3)) && printf "${grnbld}DEBUG:${clrreset} %s\n"   "$1" ; }
-  Inform(){ ((LogLevel >= 2)) && printf "${blubld}INFO:${clrreset} %s\n"    "$1" ; }
-  Warn(){   ((LogLevel >= 1)) && printf "${ylwbld}WARNING:${clrreset} %s\n" "$1" ; }
-  Err(){    ((LogLevel >= 0)) && printf "${redbld}ERROR:${clrreset} %s\n"   "$1" ; }
+  Debug(){  ((LogLevel >= 3)) && printf "$DEBUG_CLR %s\n" "$1" ; }
+  Inform(){ ((LogLevel >= 2)) && printf "$INFO_CLR %s\n"  "$1" ; }
+  Warn(){   ((LogLevel >= 1)) && printf "$WARN_CLR %s\n"  "$1" ; }
+  Err(){    ((LogLevel >= 0)) && printf "$ERROR_CLR %s\n" "$1" ; }
 
   #Use for multiple lines of a single message, no-logfile==only-stdout
   DebugCont(){  ((LogLevel >= 3)) && printf '%0.7s%s\n' "$pad" "$1" ; }
@@ -162,10 +166,10 @@ elif [[ "$LogType" = 'stdout' ]] ; then
 
 elif [[ "$LogType" = 'stderr' ]] ; then
   #Functions defining the different logging messages, no-logfile==only-stderr
-  Debug(){  ((LogLevel >= 3)) && printf "${grnbld}DEBUG:${clrreset} %s\n"   "$1" 1>&2 ; }
-  Inform(){ ((LogLevel >= 2)) && printf "${blubld}INFO:${clrreset} %s\n"    "$1" 1>&2 ; }
-  Warn(){   ((LogLevel >= 1)) && printf "${ylwbld}WARNING:${clrreset} %s\n" "$1" 1>&2 ; }
-  Err(){    ((LogLevel >= 0)) && printf "${redbld}ERROR:${clrreset} %s\n"   "$1" 1>&2 ; }
+  Debug(){  ((LogLevel >= 3)) && printf "$DEBUG_CLR %s\n" "$1" 1>&2 ; }
+  Inform(){ ((LogLevel >= 2)) && printf "$INFO_CLR %s\n"  "$1" 1>&2 ; }
+  Warn(){   ((LogLevel >= 1)) && printf "$WARN_CLR %s\n"  "$1" 1>&2 ; }
+  Err(){    ((LogLevel >= 0)) && printf "$ERROR_CLR %s\n" "$1" 1>&2 ; }
 
   #Use for multiple lines of a single message, no-logfile==only-stderr
   DebugCont(){  ((LogLevel >= 3)) && printf '%0.7s%s\n' "$pad" "$1" 1>&2 ; }
@@ -193,7 +197,7 @@ elif [[ "$LogType" = @(logfile|file) ]] ; then
   err_pipe(){ while IFS='' read -r msg; do msg="$1$msg"; ((LogLevel >= 0)) && printf '%s\n' "$msg" >> "$LogFile"; done; }
 
 else
-  printf "${redbld}ERROR:${clrreset} %s\n" 'The LogType option, if provided, must be one of: "file"; "stdout"; "stderr"; "filestdout"; "filestderr".'
+  printf "$ERROR_CLR %s\n" 'The LogType option, if provided, must be one of: "file"; "stdout"; "stderr"; "filestdout"; "filestderr".'
   return 1
 fi
 
@@ -209,7 +213,7 @@ fi
 # elif [[ "$pre" = "Detailed" ]]; then
 # 	PS4='(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]} - [${SHLVL},${BASH_SUBSHELL}, $?]'$'\n'
 # else
-# 	{ printf "${redbld}ERROR:${clrreset} %s\n" "Prepend arg must be ['Simple' | 'Detailed'] eg: ${BASH_SOURCE[0]} 'Detailed'" ; return 1 ; }
+# 	{ printf "$ERROR_CLR %s\n" "Prepend arg must be ['Simple' | 'Detailed'] eg: ${BASH_SOURCE[0]} 'Detailed'" ; return 1 ; }
 # fi
 # set -x
 #
